## TO DO

# version: "3"

# services:
#   nginx:
#     build:
#       context: ./
#       dockerfile: docker/prod/nginx/Dockerfile
#     volumes:
#       - ./api/storage:/var/www/api/storage
#       - ./api/public:/var/www/api/public
#       - ./docker/prod/logs/nginx:/var/log/nginx
#     ports:
#       - "127.0.0.1:8005:83" # Client port
#       - "127.0.0.1:8004:84" # Laravel port
#     depends_on:
#       - client
#       - php
#     restart: always

#   php:
#     build:
#       context: ./
#       dockerfile: docker/prod/php/Dockerfile
#     image: php-fpm-mysql
#     volumes:
#       - ./api/public:/var/www/api/public
#       - ./api/storage:/var/www/api/storage
#     depends_on:
#       - mysql
#       - redis
#     restart: always

#   supervisor:
#     image: php-fpm-mysql
#     restart: always
#     volumes:
#       - ./docker/prod/logs/supervisor:/var/log
#     depends_on:
#       - mysql
#       - redis
#       - php
#     command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

#   redis:
#     image: redis:6.2
#     command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
#     restart: always
#     volumes:
#       - redis:/data

#   mysql:
#     image: mariadb:10.6
#     restart: always
#     volumes:
#       - mariadb-data:/var/lib/mysql
#       - ./docker/dev/mysql/dumps/:/tmp/
#     ports:
#       - "127.0.0.1:3307:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

#   client:
#     build:
#       context: ./
#       dockerfile: docker/prod/client/Dockerfile
#     restart: always

# volumes:
#   mariadb-data:
#     driver: local
#   redis:
#     driver: local
